AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 300

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.7
      Layers:
        - Ref: HelloWorldLayer

  HelloWorldLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: hello-world-layer
      Description: Dependencies for hello world
      # NOTE on ContentUri: you must have populated dependencies/python, `sam deploy` create a layer version with
      # empty zip. However, this poses a problem when developing on non-Linux:
      # - `pip install` will install non-Linux packages, then
      # - `sam deploy` will upload & deploy a non-Linux layer.
      #
      # As for why this behavior happens, see these:
      # - https://github.com/awslabs/aws-sam-cli/issues/1481#issuecomment-546957976
      # - https://github.com/awslabs/aws-sam-cli/issues/756#issuecomment-493143635
      ContentUri: dependencies/
      CompatibleRuntimes:
        - python3.8
      LicenseInfo: "MIT"
      RetentionPolicy: Delete

Outputs:
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
